import { addImports, addPlugin, addServerHandler, addServerImports, addServerPlugin, addTypeTemplate, createResolver, defineNuxtModule, findPath } from '@nuxt/kit'
import { join, relative } from 'pathe'
import { defu } from 'defu'
import type { ModuleOptions } from './runtime/types'
import { DEFAULTS } from './runtime/utils/defaults'
import { logger } from './utils/logger'

export type {
  FeatureFlagsConfigInput,
  FeatureFlagsHelpers,
  FlagConfig,
  FlagDefinition,
  FlagsContext,
  FlagsSchema,
  FlagValue,
  FlagVariant,
  ModuleOptions,
  ResolvedFlag,
  ResolvedFlags,
} from './runtime/types'

type RuntimeOptions = Pick<ModuleOptions, 'flags' | 'cacheTTL'>

declare module 'nuxt/schema' {
  interface RuntimeConfig {
    featureFlags: RuntimeOptions
  }
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-feature-flags',
    configKey: 'featureFlags',
    compatibility: {
      nuxt: '>=3.1.0',
    },
  },
  defaults: {
    flags: {},
    cacheTTL: DEFAULTS.CACHE_TTL,
  },
  async setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)
    const typesPath = join(nuxt.options.buildDir, 'types/nuxt-feature-flags.d.ts')

    const configPath = options.config ? await resolveConfigFile(options.config, nuxt.options.rootDir) : undefined
    if (configPath) {
      // A config change also changes the generated flag names: restart to regenerate them.
      nuxt.options.watch.push(configPath)
    }

    nuxt.options.alias['#feature-flags/config'] = configPath ?? resolver.resolve('./runtime/feature-flags.config')
    nuxt.options.alias['#feature-flags/handler'] = resolver.resolve('./runtime/server/handlers/feature-flags')
    nuxt.options.alias['#feature-flags/server/utils'] = resolver.resolve('./runtime/server/utils/feature-flags')
    nuxt.options.alias['#feature-flags/types'] = typesPath

    // Server-only: flag *definitions* (weights, disabled flags...) never reach the client,
    // only each visitor's resolved flags do. Inline flags can be overridden per environment,
    // e.g. `NUXT_FEATURE_FLAGS_FLAGS_NEW_DASHBOARD=false`.
    const runtimeOptions: RuntimeOptions = { flags: options.flags, cacheTTL: options.cacheTTL }
    nuxt.options.runtimeConfig.featureFlags = defu(nuxt.options.runtimeConfig.featureFlags, runtimeOptions) as RuntimeOptions

    addPlugin(resolver.resolve('./runtime/app/plugins/feature-flag.server'))
    addPlugin(resolver.resolve('./runtime/app/plugins/feature-flag.client'))

    addImports([
      { name: 'useFeatureFlags', from: resolver.resolve('./runtime/app/composables/feature-flags') },
      { name: 'useAsyncFeatureFlags', from: resolver.resolve('./runtime/app/composables/use-async-feature-flags') },
    ])

    addServerImports(['getFeatureFlags', 'resolveFeatureFlags'].map(name => ({
      name,
      from: resolver.resolve('./runtime/server/utils/feature-flags'),
    })))

    addServerPlugin(resolver.resolve('./runtime/server/plugins/feature-flags'))
    addServerHandler({
      route: DEFAULTS.API_ROUTE,
      method: 'get',
      handler: resolver.resolve('./runtime/server/api/feature-flags.get'),
    })

    addTypeTemplate({
      filename: 'types/nuxt-feature-flags.d.ts',
      getContents: () => generateFlagTypes({
        typesDir: join(nuxt.options.buildDir, 'types'),
        configPath,
        inlineFlagNames: Object.keys(options.flags ?? {}),
        runtimeTypesPath: resolver.resolve('./runtime/types'),
      }),
    })

    nuxt.hook('prepare:types', ({ tsConfig }) => {
      if (configPath) {
        // Type-check the config file together with the app, so `#feature-flags/handler` resolves in it.
        tsConfig.include ||= []
        tsConfig.include.push(relative(nuxt.options.buildDir, configPath))
      }
    })
  },
})

async function resolveConfigFile(config: string, rootDir: string): Promise<string> {
  const path = await findPath(config, { cwd: rootDir })
  if (!path) {
    throw new Error(
      `[nuxt-feature-flags] Config file "${config}" not found (resolved from ${rootDir}). `
      + 'Fix `featureFlags.config` in nuxt.config, or remove it to use inline flags only.',
    )
  }
  logger.debug(`Using feature flags config file ${path}`)
  return path
}

function generateFlagTypes(input: { typesDir: string, configPath?: string, inlineFlagNames: string[], runtimeTypesPath: string }): string {
  const importPath = (path: string) => {
    const relativePath = relative(input.typesDir, path).replace(/\.[cm]?[jt]s$/, '')
    return relativePath.startsWith('.') ? relativePath : `./${relativePath}`
  }

  const inlineNames = input.inlineFlagNames.map(name => JSON.stringify(name)).join(' | ') || 'never'
  const configNames = input.configPath
    ? `ConfigFlagNames<typeof import(${JSON.stringify(importPath(input.configPath))})['default']>`
    : 'never'

  return `// Generated by nuxt-feature-flags
type ConfigFlags<T> = T extends (...args: any[]) => infer R ? Awaited<R> : T
type ConfigFlagNames<T> = Extract<keyof ConfigFlags<T>, string>
type KnownFlagNames = ${configNames} | ${inlineNames}

/** Every declared flag name. Falls back to \`string\` when names can't be inferred. */
export type FlagName = [KnownFlagNames] extends [never] ? string : KnownFlagNames

export type { FlagValue, FlagsSchema, ResolvedFlag, ResolvedFlags } from ${JSON.stringify(importPath(input.runtimeTypesPath))}
`
}
